### PR TITLE
Update README with Adaptable.io

### PR DESCRIPTION
**Pull request by mterrel**
I added Adaptable.io to the comparison.

### CODE REVIEW

**Review by DmitryScaletta — CHANGES_REQUESTED** [review]

**Comment by DmitryScaletta** [comment]
Thank you for the PR.
I added a few suggestions.

And also I have a couple of questions.

Can you also explain this phrase "Your app cannot perform background activities outside the scope of request handling"?
Does it mean that I can't use Adaptable.io as a websocket server or client or run cron jobs (from `@nestjs/schedule` for example)?

How exactly Adaptable.io shuts down projects for inactivity?

**Comment by mterrel** [comment]
> Thank you for the PR. I added a few suggestions.

I think I addressed your comments in the latest revision. Please check to make sure I addressed your concerns.

> Can you also explain this phrase "Your app cannot perform background activities outside the scope of request handling"? Does it mean that I can't use Adaptable.io as a websocket server or client or run cron jobs (from `@nestjs/schedule` for example)?

You referenced the important point in one of your earlier comments: "Your app's CPU allocation is set to zero when your app is not processing a network request." So for your first example, that means that your app won't be idle while there's an active web socket. (Adaptable does fully support web sockets.) But if there aren't any active network requests, you won't be able to run timed jobs like `@nestjs/schedule` because the app won't be allocated CPU between requests.



> How exactly Adaptable.io shuts down projects for inactivity?

In the free tier, when an app is not processing any network requests, the app is set to idle (the CPU allocation is set to zero) until the next request comes in. If no new network requests arrive for the app for about 15 minutes, the app is shut down gracefully with SIGTERM. When another network request arrives, the app is started again. Typical response time for that first request on a cold start is around 4-5 seconds on a typical Node.js app. The professional plan allows apps to use CPU continuously, if desired.

**Comment by DmitryScaletta** [comment]
Thank you for your answers and for the PR.

**Comment by mterrel** [comment]
@DmitryScaletta Thanks for adding Adaptable!

**Pull request merged**
